plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.0.2'
}

group = 'ru.allin'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.121-stable'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

shadowJar {
    archiveClassifier = ''
    relocate 'org.sqlite', 'ru.allin.factions.libs.sqlite'
}

build.dependsOn shadowJar
