package ru.allin.factions.service;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitRunnable;
import ru.allin.factions.data.Database;
import ru.allin.factions.economy.EconomyHook;
import ru.allin.factions.model.*;
import ru.allin.factions.util.Text;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public final class InquisitionService {
    private final JavaPlugin plugin; private final Database db; private final FactionService factions; private final EconomyHook economy;
    private final NamespacedKey batonKey; private final NamespacedKey ownerKey;
    private final Map<UUID, ArrestProgress> arrests=new ConcurrentHashMap<>();
    private final Set<UUID> readOnlySearchers=ConcurrentHashMap.newKeySet();
    public InquisitionService(JavaPlugin plugin,Database db,FactionService factions,EconomyHook economy){this.plugin=plugin;this.db=db;this.factions=factions;this.economy=economy;batonKey=new NamespacedKey(plugin,"baton");ownerKey=new NamespacedKey(plugin,"baton_owner");}
    public boolean warn(Player issuer,Player target){PlayerData i=factions.data(issuer);if(i.faction()!=FactionType.INQUISITION||i.rank()==null)return false;long now=System.currentTimeMillis();if(i.rank()==FactionRank.INITIATE){long cd=plugin.getConfig().getLong("inquisition.warns.initiate-cooldown-seconds",600)*1000L;if(now-i.lastWarnAt()<cd){issuer.sendMessage(Text.msg("Следующий варн через "+Text.time((cd-(now-i.lastWarnAt()))/1000)+"."));return true;}}PlayerData t=factions.data(target);int warns=t.warns()+1;boolean wanted=warns>=plugin.getConfig().getInt("inquisition.warns.wanted-after",3);db.updatePlayer(issuer.getUniqueId(),"last_warn=?",now);db.updatePlayer(target.getUniqueId(),"warns=?,wanted=?,wanted_since=?",warns,wanted?1:0,wanted?(t.wanted()?t.wantedSince():now):0);db.addStat(issuer.getUniqueId(),"warns_issued",1);issuer.sendMessage(Text.msg("Игроку "+target.getName()+" выдан варн. Текущих: "+warns));target.sendMessage(Text.msg("Вы получили предупреждение от Инквизиции. Текущих: "+warns));if(wanted&&!t.wanted()){Bukkit.broadcast(Component.text("🚨 "+target.getName()+" объявлен в розыск!",NamedTextColor.RED));}db.log(issuer.getName(),"WARN",target.getUniqueId()+" warns="+warns);return true;}
    public void search(Player issuer,Player target){PlayerData i=factions.data(issuer);if(i.faction()!=FactionType.INQUISITION||!(i.rank()==FactionRank.INQUISITOR||i.rank()==FactionRank.MASTER)){issuer.sendMessage(Text.msg("Досмотр доступен только Инквизитору и Магистру."));return;}double max=plugin.getConfig().getDouble("inquisition.search.max-distance",3.0);if(!issuer.getWorld().equals(target.getWorld())||issuer.getLocation().distanceSquared(target.getLocation())>max*max){issuer.sendMessage(Text.msg("Подойдите ближе к игроку."));return;}long now=System.currentTimeMillis(),cd=plugin.getConfig().getLong("inquisition.search.cooldown-seconds",300)*1000L;if(now-i.lastSearchAt()<cd){issuer.sendMessage(Text.msg("Досмотр доступен через "+Text.time((cd-(now-i.lastSearchAt()))/1000)+"."));return;}int duration=plugin.getConfig().getInt("inquisition.search.duration-seconds",10);Location start=target.getLocation().clone();issuer.sendMessage(Text.msg("Досмотр начат. Не отходите от цели."));new BukkitRunnable(){int left=duration;public void run(){if(!issuer.isOnline()||!target.isOnline()||!issuer.getWorld().equals(target.getWorld())||issuer.getLocation().distanceSquared(target.getLocation())>max*max||target.getLocation().distanceSquared(start)>max*max){issuer.sendMessage(Text.msg("Досмотр отменён."));cancel();return;}issuer.sendActionBar(Component.text("🔍 ДОСМОТР: "+left+"с",NamedTextColor.YELLOW));if(--left<=0){db.updatePlayer(issuer.getUniqueId(),"last_search=?",System.currentTimeMillis());db.addStat(issuer.getUniqueId(),"searches",1);readOnlySearchers.add(issuer.getUniqueId());issuer.openInventory(target.getInventory());issuer.sendMessage(Text.msg("Досмотр завершён. Инвентарь открыт только для просмотра."));cancel();}}}.runTaskTimer(plugin,0,20);}
    public ItemStack createBaton(Player p){ItemStack s=new ItemStack(Material.STICK);ItemMeta m=s.getItemMeta();m.displayName(Component.text("ПАЛКА-ДУБИНКА",NamedTextColor.DARK_RED));m.getPersistentDataContainer().set(batonKey,PersistentDataType.BYTE,(byte)1);m.getPersistentDataContainer().set(ownerKey,PersistentDataType.STRING,p.getUniqueId().toString());s.setItemMeta(m);return s;}
    public boolean giveBaton(Player p){PlayerData d=factions.data(p);if(d.faction()!=FactionType.INQUISITION||!(d.rank()==FactionRank.INQUISITOR||d.rank()==FactionRank.MASTER)){p.sendMessage(Text.msg("Дубинка доступна только Инквизитору и Магистру."));return false;}long cd=plugin.getConfig().getLong("inquisition.baton.receive-cooldown-hours",24)*3600000L,now=System.currentTimeMillis();if(now-d.lastBatonAt()<cd){p.sendMessage(Text.msg("Следующая дубинка через "+Text.time((cd-(now-d.lastBatonAt()))/1000)+"."));return false;}removeBatons(p);p.getInventory().addItem(createBaton(p));db.updatePlayer(p.getUniqueId(),"last_baton=?",now);p.sendMessage(Text.msg("Вы получили Палку-Дубинку."));return true;}
    public boolean isBaton(ItemStack i,Player owner){if(i==null||!i.hasItemMeta())return false;ItemMeta m=i.getItemMeta();Byte b=m.getPersistentDataContainer().get(batonKey,PersistentDataType.BYTE);String o=m.getPersistentDataContainer().get(ownerKey,PersistentDataType.STRING);return b!=null&&b==1&&owner.getUniqueId().toString().equals(o);}
    public boolean isAnyBaton(ItemStack i){return i!=null&&i.hasItemMeta()&&i.getItemMeta().getPersistentDataContainer().has(batonKey,PersistentDataType.BYTE);}
    public void removeBatons(Player p){for(int x=0;x<p.getInventory().getSize();x++){ItemStack i=p.getInventory().getItem(x);if(isAnyBaton(i))p.getInventory().setItem(x,null);}}
    public void batonHit(Player officer,Player target){PlayerData od=factions.data(officer),td=factions.data(target);if(od.faction()!=FactionType.INQUISITION||!td.wanted())return;long now=System.currentTimeMillis();ArrestProgress prev=arrests.get(target.getUniqueId());long reset=plugin.getConfig().getLong("inquisition.baton.progress-reset-seconds",30)*1000L;int hits=(prev==null||now-prev.lastHit>reset)?1:prev.hits+1;arrests.put(target.getUniqueId(),new ArrestProgress(hits,now));int need=plugin.getConfig().getInt("inquisition.baton.hits-to-arrest",10);officer.sendActionBar(Component.text("🚨 ЗАДЕРЖАНИЕ "+hits+"/"+need,NamedTextColor.RED));target.sendActionBar(Component.text("🚨 ЗАДЕРЖАНИЕ "+hits+"/"+need,NamedTextColor.RED));if(hits>=need){arrests.remove(target.getUniqueId());jail(target);db.addStat(officer.getUniqueId(),"arrests",1);}}
    public void jail(Player p){PlayerData d=factions.data(p);int count=d.imprisonments()+1;long minutes=plugin.getConfig().getLong("prison.sentence.first-minutes",30)+plugin.getConfig().getLong("prison.sentence.additional-minutes-per-imprisonment",5)*(count-1L);db.updatePlayer(p.getUniqueId(),"imprisonments=?,prison_remaining=?",count,minutes*60);List<Location> spawns=db.locations(LocationType.PRISON_SPAWN);if(!spawns.isEmpty())p.teleportAsync(spawns.get(0));p.sendMessage(Text.msg("Вы отправлены в тюрьму на "+minutes+" минут."));db.log("INQUISITION","JAIL",p.getUniqueId()+" "+minutes+"m");}
    public void release(Player p){db.updatePlayer(p.getUniqueId(),"prison_remaining=0,warns=0,wanted=0,wanted_since=0");Location spawn=p.getWorld().getSpawnLocation();if(Bukkit.getWorlds().size()>0)spawn=Bukkit.getWorlds().get(0).getSpawnLocation();p.teleportAsync(spawn);p.sendMessage(Text.msg("Срок отбыт. Вы освобождены и телепортированы на спавн."));db.log("SYSTEM","PRISON_RELEASE",p.getUniqueId().toString());}
    public void tickPrison(){for(Player p:Bukkit.getOnlinePlayers()){PlayerData d=factions.data(p);if(d.prisonRemainingSeconds()<=0)continue;long next=d.prisonRemainingSeconds()-1;db.updatePlayer(p.getUniqueId(),"prison_remaining=?",next);p.sendActionBar(Component.text("🔒 Осталось: "+Text.time(next),NamedTextColor.RED));if(next<=0)release(p);}}
    public void toilet(Player p,Location block){PlayerData d=factions.data(p);if(!d.jailed())return;boolean registered=db.locations(LocationType.TOILET).stream().anyMatch(l->l.getWorld().equals(block.getWorld())&&l.distanceSquared(block)<2.0);if(!registered)return;int sec=plugin.getConfig().getInt("prison.toilet.duration-seconds",10);Location start=p.getLocation().clone();new BukkitRunnable(){int left=sec;public void run(){if(!p.isOnline()||p.getLocation().distanceSquared(start)>9){p.sendMessage(Text.msg("Работа отменена."));cancel();return;}p.sendActionBar(Component.text("🧽 ДРАИТЬ ТОЛЧЕК: "+left+"с",NamedTextColor.YELLOW));if(--left<=0){double reward=plugin.getConfig().getDouble("prison.toilet.reward",1);if(economy.deposit(p,reward)){db.addStat(p.getUniqueId(),"prison_work",1);p.sendMessage(Text.msg("Работа выполнена: +"+Text.money(reward)));}cancel();}}}.runTaskTimer(plugin,0,20);}
    public boolean isReadOnlySearcher(Player p){return readOnlySearchers.contains(p.getUniqueId());}
    public void endReadOnlySearch(Player p){readOnlySearchers.remove(p.getUniqueId());}
    private record ArrestProgress(int hits,long lastHit){}
}
