package ru.allin.factions.service;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.scheduler.BukkitRunnable;
import ru.allin.factions.data.Database;
import ru.allin.factions.economy.EconomyHook;
import ru.allin.factions.model.*;
import ru.allin.factions.util.Text;

import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

public final class ThiefService {
    private final JavaPlugin plugin; private final Database db; private final FactionService factions; private final EconomyHook economy;
    private final NamespacedKey contrabandKey,ownerKey,operationKey;
    public ThiefService(JavaPlugin plugin,Database db,FactionService factions,EconomyHook economy){this.plugin=plugin;this.db=db;this.factions=factions;this.economy=economy;contrabandKey=new NamespacedKey(plugin,"contraband");ownerKey=new NamespacedKey(plugin,"contraband_owner");operationKey=new NamespacedKey(plugin,"contraband_operation");}
    public void steal(Player thief,Player target){PlayerData d=factions.data(thief);if(d.faction()!=FactionType.THIEVES){thief.sendMessage(Text.msg("Кражи доступны только Гильдии воров."));return;}if(thief.equals(target)){thief.sendMessage(Text.msg("Нельзя обокрасть самого себя."));return;}double max=plugin.getConfig().getDouble("thieves.stealing.max-distance",5);if(!sameRange(thief,target,max)){thief.sendMessage(Text.msg("Цель должна находиться не дальше 5 блоков."));return;}long now=System.currentTimeMillis(),cd=plugin.getConfig().getLong("thieves.stealing.cooldown-seconds",600)*1000L;if(now-d.lastStealAt()<cd){thief.sendMessage(Text.msg("Следующая кража через "+Text.time((cd-(now-d.lastStealAt()))/1000)+"."));return;}int duration=plugin.getConfig().getInt("thieves.stealing.duration-seconds",5);thief.sendMessage(Text.msg("Попытка кражи началась..."));new BukkitRunnable(){int left=duration;public void run(){if(!thief.isOnline()||!target.isOnline()||!sameRange(thief,target,max)){if(thief.isOnline())thief.sendMessage(Text.msg("Кража отменена. Кулдаун не потрачен."));cancel();return;}thief.sendActionBar(Component.text("🥷 КРАЖА: "+left+"с",NamedTextColor.LIGHT_PURPLE));if(--left<=0){resolveSteal(thief,target);cancel();}}}.runTaskTimer(plugin,0,20);}
    private void resolveSteal(Player thief,Player target){db.updatePlayer(thief.getUniqueId(),"last_steal=?",System.currentTimeMillis());db.addStat(thief.getUniqueId(),"theft_attempts",1);double chance=plugin.getConfig().getDouble("thieves.stealing.success-chance",.2);if(ThreadLocalRandom.current().nextDouble()>=chance){db.addStat(thief.getUniqueId(),"theft_failures",1);thief.sendMessage(Text.msg("❌ Вас заметили! Кража провалилась."));if(plugin.getConfig().getBoolean("thieves.stealing.notify-victim-on-failure",true))target.sendMessage(Text.msg("🚨 "+thief.getName()+" пытался вас обокрасть! Вы можете сообщить Инквизиции."));db.log(thief.getName(),"STEAL_FAIL",target.getUniqueId().toString());return;}boolean preferOre=ThreadLocalRandom.current().nextBoolean();boolean done=preferOre?stealOre(thief,target):stealMoney(thief,target);if(!done)done=preferOre?stealMoney(thief,target):stealOre(thief,target);db.addStat(thief.getUniqueId(),"theft_successes",1);if(!done)thief.sendMessage(Text.msg("Кража удалась, но у цели нечего красть."));db.log(thief.getName(),"STEAL_SUCCESS",target.getUniqueId().toString());}
    private boolean stealMoney(Player thief,Player target){double min=plugin.getConfig().getDouble("thieves.stealing.money.min",5),max=plugin.getConfig().getDouble("thieves.stealing.money.max",20);double available=economy.balance(target);if(available<min)return false;double amount=Math.min(available,ThreadLocalRandom.current().nextDouble(min,max+0.0001));amount=Math.floor(amount);if(!economy.withdraw(target,amount))return false;if(!economy.deposit(thief,amount)){economy.deposit(target,amount);return false;}db.addStat(thief.getUniqueId(),"money_stolen",amount);thief.sendMessage(Text.msg("🥷 Кража успешна! Украдено "+Text.money(amount)+"."));return true;}
    private boolean stealOre(Player thief,Player target){List<String> names=plugin.getConfig().getStringList("thieves.stealing.allowed-ores");List<Integer> slots=new ArrayList<>();for(int i=0;i<target.getInventory().getSize();i++){ItemStack it=target.getInventory().getItem(i);if(it!=null&&names.contains(it.getType().name()))slots.add(i);}if(slots.isEmpty())return false;int slot=slots.get(ThreadLocalRandom.current().nextInt(slots.size()));ItemStack it=target.getInventory().getItem(slot);int min=plugin.getConfig().getInt("thieves.stealing.ore.min",1),max=plugin.getConfig().getInt("thieves.stealing.ore.max",2);int amount=Math.min(it.getAmount(),ThreadLocalRandom.current().nextInt(min,max+1));ItemStack reward=it.clone();reward.setAmount(amount);it.setAmount(it.getAmount()-amount);if(it.getAmount()<=0)target.getInventory().setItem(slot,null);else target.getInventory().setItem(slot,it);Map<Integer,ItemStack> overflow=thief.getInventory().addItem(reward);overflow.values().forEach(x->thief.getWorld().dropItemNaturally(thief.getLocation(),x));db.addStat(thief.getUniqueId(),"items_stolen",amount);thief.sendMessage(Text.msg("🥷 Кража успешна! Украдено: "+amount+" × "+reward.getType().name()+"."));return true;}
    private boolean sameRange(Player a,Player b,double max){return a.getWorld().equals(b.getWorld())&&a.getLocation().distanceSquared(b.getLocation())<=max*max;}
    public boolean hasInquisitionOnline(){for(Player p:Bukkit.getOnlinePlayers())if(factions.data(p).faction()==FactionType.INQUISITION)return true;return false;}
    public void startContraband(Player p){PlayerData d=factions.data(p);if(d.faction()!=FactionType.THIEVES){p.sendMessage(Text.msg("Контрабанда доступна только Гильдии воров."));return;}if(db.contrabandAmount(p.getUniqueId())>0){p.sendMessage(Text.msg("У вас уже есть активная контрабанда."));return;}if(plugin.getConfig().getBoolean("thieves.contraband.require-inquisition-online",true)&&!hasInquisitionOnline()){p.sendMessage(Text.msg("Контрабанда недоступна: Инквизиция не ONLINE."));return;}int sec=plugin.getConfig().getInt("thieves.contraband.pickup-duration-seconds",5);Location start=p.getLocation().clone();new BukkitRunnable(){int left=sec;public void run(){if(!p.isOnline()||p.getLocation().distanceSquared(start)>9){if(p.isOnline())p.sendMessage(Text.msg("Получение груза отменено."));cancel();return;}p.sendActionBar(Component.text("📦 ПОЛУЧЕНИЕ: "+left+"с",NamedTextColor.LIGHT_PURPLE));if(--left<=0){giveContraband(p);cancel();}}}.runTaskTimer(plugin,0,20);}
    private void giveContraband(Player p){int min=plugin.getConfig().getInt("thieves.contraband.amount.min",1),max=plugin.getConfig().getInt("thieves.contraband.amount.max",3);int amount=ThreadLocalRandom.current().nextInt(min,max+1);UUID op=UUID.randomUUID();ItemStack item=createContraband(p,op,amount);p.getInventory().addItem(item);db.setContraband(p.getUniqueId(),op,amount,"ACTIVE");applyCarryEffects(p);p.sendMessage(Text.msg("Контрабанда получена: "+amount+" шт. Доставьте её на финишный маяк."));db.addStat(p.getUniqueId(),"contraband_started",1);}
    private ItemStack createContraband(Player p,UUID op,int amount){ItemStack i=new ItemStack(Material.ECHO_SHARD,amount);ItemMeta m=i.getItemMeta();m.displayName(Component.text("КОНТРАБАНДА",NamedTextColor.LIGHT_PURPLE));m.getPersistentDataContainer().set(contrabandKey,PersistentDataType.BYTE,(byte)1);m.getPersistentDataContainer().set(ownerKey,PersistentDataType.STRING,p.getUniqueId().toString());m.getPersistentDataContainer().set(operationKey,PersistentDataType.STRING,op.toString());i.setItemMeta(m);return i;}
    public boolean isContraband(ItemStack i){return i!=null&&i.hasItemMeta()&&i.getItemMeta().getPersistentDataContainer().has(contrabandKey,PersistentDataType.BYTE);}
    public boolean isOwnedContraband(ItemStack i,Player p){if(!isContraband(i))return false;return p.getUniqueId().toString().equals(i.getItemMeta().getPersistentDataContainer().get(ownerKey,PersistentDataType.STRING));}
    public void deliverContraband(Player p){int dbAmount=db.contrabandAmount(p.getUniqueId());if(dbAmount<=0){p.sendMessage(Text.msg("У вас нет активной контрабанды."));return;}int actual=countContraband(p);if(actual<=0){p.sendMessage(Text.msg("Контрабанда не найдена в инвентаре."));return;}int sec=plugin.getConfig().getInt("thieves.contraband.delivery-duration-seconds",10);double max=plugin.getConfig().getDouble("thieves.contraband.delivery-max-distance",3);Location start=p.getLocation().clone();new BukkitRunnable(){int left=sec;public void run(){if(!p.isOnline()||!p.getWorld().equals(start.getWorld())||p.getLocation().distanceSquared(start)>max*max){if(p.isOnline())p.sendMessage(Text.msg("Передача контрабанды сорвана. Груз сохранён."));cancel();return;}p.sendActionBar(Component.text("📦 ПЕРЕДАЧА: "+left+"с",NamedTextColor.LIGHT_PURPLE));if(--left<=0){finishDelivery(p);cancel();}}}.runTaskTimer(plugin,0,20);}
    private void finishDelivery(Player p){int count=removeContraband(p);if(count<=0)return;double min=plugin.getConfig().getDouble("thieves.contraband.reward-per-item.min",80),max=plugin.getConfig().getDouble("thieves.contraband.reward-per-item.max",100),total=0;for(int i=0;i<count;i++)total+=Math.floor(ThreadLocalRandom.current().nextDouble(min,max+1));economy.deposit(p,total);db.clearContraband(p.getUniqueId());clearCarryEffects(p);db.addStat(p.getUniqueId(),"contraband_delivered",count);db.addStat(p.getUniqueId(),"contraband_money",total);p.sendMessage(Text.msg("Контрабанда доставлена: "+count+" шт., получено "+Text.money(total)+"."));}
    public int countContraband(Player p){int c=0;for(ItemStack i:p.getInventory().getContents())if(isOwnedContraband(i,p))c+=i.getAmount();return c;}
    public int removeContraband(Player p){int c=0;for(int s=0;s<p.getInventory().getSize();s++){ItemStack i=p.getInventory().getItem(s);if(isOwnedContraband(i,p)){c+=i.getAmount();p.getInventory().setItem(s,null);}}return c;}
    public void loseContraband(Player p){int c=removeContraband(p);if(c>0||db.contrabandAmount(p.getUniqueId())>0){db.clearContraband(p.getUniqueId());db.addStat(p.getUniqueId(),"contraband_lost",1);clearCarryEffects(p);p.sendMessage(Text.msg("💀 Контрабанда потеряна."));}}
    public void applyCarryEffects(Player p){if(db.contrabandAmount(p.getUniqueId())<=0)return;p.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS,20*60*60,2,false,false,true));}
    public void clearCarryEffects(Player p){p.removePotionEffect(PotionEffectType.SLOWNESS);}
}
