package ru.allin.factions.gui;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;
import ru.allin.factions.data.Database;
import ru.allin.factions.model.*;
import ru.allin.factions.service.*;
import ru.allin.factions.util.Text;

import java.util.*;

public final class GuiService {
    private final JavaPlugin plugin; private final Database db; private final FactionService factions; private final InquisitionService inq;
    private final NamespacedKey actionKey;
    public GuiService(JavaPlugin plugin,Database db,FactionService factions,InquisitionService inq){this.plugin=plugin;this.db=db;this.factions=factions;this.inq=inq;this.actionKey=new NamespacedKey(plugin,"gui_action");}

    public void open(Player p){PlayerData d=factions.data(p);if(d.faction()==null)openSelect(p);else openFaction(p,d);}
    private void openSelect(Player p){Inventory inv=Bukkit.createInventory(null,54,Component.text("ALLIN • Выбор фракции",NamedTextColor.GOLD));fill(inv,Material.BLACK_STAINED_GLASS_PANE);inv.setItem(20,button(Material.RED_BANNER,"join:INQUISITION",Component.text("ИНКВИЗИЦИЯ",NamedTextColor.RED),List.of(Component.text("Закон, порядок и власть."),Component.text("Варны • розыск • досмотры • тюрьма"),Component.text("Нажмите для вступления",NamedTextColor.YELLOW))));inv.setItem(22,button(Material.ECHO_SHARD,"join:THIEVES",Component.text("ГИЛЬДИЯ ВОРОВ",NamedTextColor.LIGHT_PURPLE),List.of(Component.text("Риск, криминал и большие деньги."),Component.text("Кражи • контрабанда • операции"),Component.text("Нажмите для вступления",NamedTextColor.YELLOW))));inv.setItem(24,button(Material.IRON_PICKAXE,"join:WORKERS",Component.text("РАБОТЯГИ",NamedTextColor.GREEN),List.of(Component.text("Стабильность, труд и развитие."),Component.text("Зарплата • профессии • бонус ×2"),Component.text("Нажмите для вступления",NamedTextColor.YELLOW))));if(p.hasPermission("allinfactions.admin"))inv.setItem(53,button(Material.COMMAND_BLOCK,"admin",Component.text("АДМИН-ПАНЕЛЬ",NamedTextColor.RED),List.of(Component.text("Управление ALLINFactions"))));p.openInventory(inv);}
    private void openFaction(Player p,PlayerData d){Inventory inv=Bukkit.createInventory(null,54,Component.text("ALLIN • "+d.faction().display(),d.faction().color()));fill(inv,Material.BLACK_STAINED_GLASS_PANE);inv.setItem(4,button(materialFor(d.faction()),"info",Component.text(d.faction().display(),d.faction().color()),List.of(Component.text("Ранг: "+d.rank().display()),Component.text("Во фракции: "+Text.time(d.factionSeconds())),Component.text("Зарплата: "+Text.money(factions.salary(d.faction(),d.rank()))+"/ч"))));inv.setItem(10,button(Material.PLAYER_HEAD,"profile",Component.text("МОЙ ПРОФИЛЬ",NamedTextColor.AQUA),profileLore(p,d)));inv.setItem(12,button(Material.BOOK,"members",Component.text("СОСТАВ",NamedTextColor.YELLOW),List.of(Component.text("Участников: "+db.factionMembers(d.faction()).size()))));inv.setItem(19,button(Material.CHEST,"treasury",Component.text("КАЗНА",NamedTextColor.GOLD),List.of(Component.text("Баланс: "+Text.money(factions.treasury(d.faction()))),Component.text(factions.isLeader(p)?"Глава может пополнять/выводить":"Только просмотр"))));inv.setItem(21,button(Material.PAPER,"chat",Component.text("ЧАТ ФРАКЦИИ",NamedTextColor.AQUA),List.of(Component.text("Режим: "+(d.factionChat()?"Фракционный":"Общий")),Component.text("Нажмите для переключения",NamedTextColor.YELLOW))));inv.setItem(23,button(Material.CLOCK,"salary",Component.text("ЗАРПЛАТА",NamedTextColor.GREEN),List.of(Component.text("Ставка: "+Text.money(factions.salary(d.faction(),d.rank()))+"/ч"),Component.text("Долг: "+Text.money(d.salaryDebt())),Component.text("До выплаты: "+Text.time(Math.max(0,3600-d.salarySeconds()))))));inv.setItem(25,button(Material.WRITABLE_BOOK,"stats",Component.text("СТАТИСТИКА",NamedTextColor.LIGHT_PURPLE),List.of(Component.text("Открыть статистику"))));
        if(d.faction()==FactionType.INQUISITION){inv.setItem(14,button(Material.COMPASS,"wanted",Component.text("РОЗЫСК",NamedTextColor.RED),List.of(Component.text("Разыскиваемых: "+db.wantedPlayers().size()))));if(d.rank().level()>=2){inv.setItem(16,button(Material.STICK,"baton",Component.text("ПАЛКА-ДУБИНКА",NamedTextColor.DARK_RED),List.of(Component.text("10 ударов по разыскиваемому = арест"),Component.text("Получение раз в 24 часа"))));inv.setItem(30,button(Material.SPYGLASS,"search_info",Component.text("ДОСМОТР",NamedTextColor.YELLOW),List.of(Component.text("/search <ник> • 10 сек • кулдаун 5 мин"))));}inv.setItem(28,button(Material.IRON_BARS,"prison",Component.text("ТЮРЬМА",NamedTextColor.GRAY),List.of(Component.text("Первый срок 30 мин, далее +5 мин"))));}
        if(d.faction()==FactionType.THIEVES){inv.setItem(14,button(Material.GOLD_INGOT,"steal_info",Component.text("ВОРОВСТВО",NamedTextColor.LIGHT_PURPLE),List.of(Component.text("/steal <ник> • шанс 20% • 5 блоков"))));inv.setItem(16,button(Material.RECOVERY_COMPASS,"contraband_info",Component.text("КОНТРАБАНДА",NamedTextColor.LIGHT_PURPLE),List.of(Component.text("1–3 осколка • $80–100 за каждый"))));}
        if(d.faction()==FactionType.WORKERS){double chance=d.rank()==FactionRank.FACTORY_WORKER?5:10;inv.setItem(14,button(Material.DIAMOND_PICKAXE,"worker_bonus",Component.text("БОНУС ПРОФЕССИЙ",NamedTextColor.GREEN),List.of(Component.text(chance+"% шанс удвоить обычную добычу"),Component.text("Miner • Farmer • Fishing"))));inv.setItem(16,button(Material.CLOCK,"worktime",Component.text("РАБОЧЕЕ ВРЕМЯ",NamedTextColor.GREEN),List.of(Component.text("Отработано: "+Text.time(d.factionSeconds())),Component.text(d.rank()==FactionRank.FACTORY_WORKER?"До Трудоголика: "+Text.time(Math.max(0,plugin.getConfig().getLong("workers.promotion.workaholic-hours",100)*3600-d.factionSeconds())):"Трудоголик достигнут"))));}
        if(factions.isLeader(p)){inv.setItem(32,button(Material.NETHER_STAR,"management",Component.text("УПРАВЛЕНИЕ",NamedTextColor.GOLD),List.of(Component.text("Состав • зарплаты • казна • ЧС"))));inv.setItem(30,button(Material.BELL,"announce",Component.text("ОБЪЯВЛЕНИЕ",NamedTextColor.YELLOW),List.of(Component.text("Используйте /f announce <текст>"))));}
        inv.setItem(45,button(Material.BARRIER,"leave",Component.text("ПОКИНУТЬ ФРАКЦИЮ",NamedTextColor.RED),List.of(Component.text("После выхода — 24 часа без вступления"))));if(p.hasPermission("allinfactions.admin"))inv.setItem(53,button(Material.COMMAND_BLOCK,"admin",Component.text("АДМИН-ПАНЕЛЬ",NamedTextColor.RED),List.of(Component.text("Административные функции"))));p.openInventory(inv);}
    private List<Component> profileLore(Player p,PlayerData d){List<Component> l=new ArrayList<>();l.add(Component.text("Фракция: "+d.faction().display()));l.add(Component.text("Ранг: "+d.rank().display()));l.add(Component.text("Во фракции: "+Text.time(d.factionSeconds())));l.add(Component.text("Получено зарплаты: "+Text.money(db.stat(p.getUniqueId(),"salary_received"))));if(d.faction()==FactionType.INQUISITION){l.add(Component.text("Выдано варнов: "+(int)db.stat(p.getUniqueId(),"warns_issued")));l.add(Component.text("Арестов: "+(int)db.stat(p.getUniqueId(),"arrests")));l.add(Component.text("Досмотров: "+(int)db.stat(p.getUniqueId(),"searches")));}if(d.faction()==FactionType.THIEVES){l.add(Component.text("Попыток краж: "+(int)db.stat(p.getUniqueId(),"theft_attempts")));l.add(Component.text("Успешных: "+(int)db.stat(p.getUniqueId(),"theft_successes")));l.add(Component.text("Украдено денег: "+Text.money(db.stat(p.getUniqueId(),"money_stolen"))));}if(d.faction()==FactionType.WORKERS){l.add(Component.text("Бонус ×2: "+(int)db.stat(p.getUniqueId(),"worker_bonus_count")));l.add(Component.text("Доп. предметов: "+(int)db.stat(p.getUniqueId(),"worker_extra_items")));}return l;}
    private Material materialFor(FactionType f){return switch(f){case INQUISITION->Material.RED_BANNER;case THIEVES->Material.ECHO_SHARD;case WORKERS->Material.IRON_PICKAXE;};}
    private ItemStack button(Material m,String action,Component name,List<Component> lore){ItemStack i=new ItemStack(m);ItemMeta meta=i.getItemMeta();meta.displayName(name);meta.lore(lore);meta.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,action);i.setItemMeta(meta);return i;}
    private void fill(Inventory inv,Material m){ItemStack pane=new ItemStack(m);ItemMeta meta=pane.getItemMeta();meta.displayName(Component.empty());pane.setItemMeta(meta);for(int i=0;i<inv.getSize();i++)inv.setItem(i,pane);}
    public String action(ItemStack i){if(i==null||!i.hasItemMeta())return null;return i.getItemMeta().getPersistentDataContainer().get(actionKey,PersistentDataType.STRING);}
    public void click(Player p,String action){if(action==null)return;if(action.startsWith("join:")){FactionType f=FactionType.valueOf(action.substring(5));p.closeInventory();if(factions.join(p,f))open(p);return;}switch(action){case "chat"->{PlayerData d=factions.data(p);db.updatePlayer(p.getUniqueId(),"faction_chat=?",d.factionChat()?0:1);p.sendMessage(Text.msg("Режим чата: "+(d.factionChat()?"общий":"фракционный")+"."));open(p);}case "baton"->{p.closeInventory();inq.giveBaton(p);}case "leave"->{p.closeInventory();factions.leave(p,false);}case "wanted"->openWanted(p);case "members"->openMembers(p);case "admin"->openAdmin(p);default->p.sendMessage(Text.msg("Раздел доступен. Для быстрых действий используйте команды из /faction."));}}
    private void openWanted(Player p){Inventory inv=Bukkit.createInventory(null,54,Component.text("Инквизиция • Розыск",NamedTextColor.RED));int slot=0;for(PlayerData d:db.wantedPlayers()){if(slot>=45)break;ItemStack head=button(Material.PLAYER_HEAD,"none",Component.text(d.name(),NamedTextColor.RED),List.of(Component.text("Варнов: "+d.warns()),Component.text("В розыске: "+Text.time((System.currentTimeMillis()-d.wantedSince())/1000)),Component.text(Bukkit.getPlayer(d.uuid())!=null?"● ONLINE":"● OFFLINE")));inv.setItem(slot++,head);}p.openInventory(inv);}
    private void openMembers(Player p){PlayerData me=factions.data(p);if(me.faction()==null)return;Inventory inv=Bukkit.createInventory(null,54,Component.text(me.faction().display()+" • Состав",me.faction().color()));int slot=0;for(PlayerData d:db.factionMembers(me.faction())){if(slot>=45)break;inv.setItem(slot++,button(Material.PLAYER_HEAD,"none",Component.text(d.name()),List.of(Component.text("Ранг: "+d.rank().display()),Component.text("Время: "+Text.time(d.factionSeconds())))));}p.openInventory(inv);}
    private void openAdmin(Player p){if(!p.hasPermission("allinfactions.admin"))return;Inventory inv=Bukkit.createInventory(null,27,Component.text("ALLIN • Админ-панель",NamedTextColor.RED));inv.setItem(10,button(Material.NETHER_STAR,"none",Component.text("ГЛАВЫ ФРАКЦИЙ",NamedTextColor.GOLD),List.of(Component.text("/fadmin setleader <faction> <player>"))));inv.setItem(12,button(Material.IRON_BARS,"none",Component.text("ТЮРЬМА",NamedTextColor.GRAY),List.of(Component.text("/fadmin prison ..."))));inv.setItem(14,button(Material.BEACON,"none",Component.text("ТОЧКИ КОНТРАБАНДЫ",NamedTextColor.LIGHT_PURPLE),List.of(Component.text("/fadmin thieves beacon ..."))));inv.setItem(16,button(Material.GOLD_INGOT,"none",Component.text("ЭКОНОМИКА",NamedTextColor.GREEN),List.of(Component.text("/fadmin treasury / salary ..."))));p.openInventory(inv);}
}
